-- 用户表
CREATE TABLE IF NOT EXISTS user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50),
    password VARCHAR(100),
    level INT NOT NULL DEFAULT 2,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 留言表
CREATE TABLE IF NOT EXISTS message (
    id INT PRIMARY KEY AUTO_INCREMENT,
    content VARCHAR(500) NOT NULL,
    user_id INT NOT NULL,
    status TINYINT DEFAULT 1 COMMENT '1正常 0删除',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 回复表
CREATE TABLE IF NOT EXISTS message_reply (
    id INT PRIMARY KEY AUTO_INCREMENT,
    message_id INT NOT NULL,
    content VARCHAR(300) NOT NULL,
    user_id INT NOT NULL,
    status TINYINT DEFAULT 1 COMMENT '1正常 0删除',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);